baseURL = "https://nicspics.netlify.app/"
languageCode = "en-us"
title = "nicspics"
theme = "neuw"


ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]

permalinks:
  post: /:year/:month/:day/:slug/
        
        
custom_css = ["css/style.css"]        


reading_time = true

enableEmoji = true


  
menu:
  main:
    - name: Home
      url: /
    - name: random
      url: /random/tiritiri/
    - name: coromandel
      url: /post/coromandel/
    - name: nelson
      url: /post/nelson/
      
 [params]
    author = "Nic Coxen"
    dateFormat = "25/06/2016"

      

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
