baseURL = "https://nicspics.netlify.app/"
languageCode = "en-us"
title = "nicspics"
theme = "neuw"
uglyurls = true


ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]

permalinks:
  post: /:year/:month/:day/:slug/
  
[related]
    threshold = 0 
    includeNewer = true
    toLower = false

    [[related.indices]]
        name = "categories"
        weight = 100

    [[related.indices]]
        name = "date"
        weight = 10
        


reading_time = true

enableEmoji = true

preserveTaxonomyNames = true
  
menu:
  main:
    - name: Home
      url: /
    - name: About
      url: /About/
    - name: coromandel
      url: /post/coromandel/

      




reading_time = true

enableEmoji = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
