baseURL = "https://nicspics.netlify.app/"
languageCode = "en-us"
title = "nicspics"
theme = "neuw"
canonifyurls = true
paginate = 10

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    pre = "pen-tool"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3



reading_time = true

enableEmoji = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true