baseURL = '/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'neuw'

      
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
  


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
